name: Update Contributors

on:
  pull_request:
    types:
      - closed

jobs:
  add-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add contributor with emoji
        uses: all-contributors/all-contributors-action@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          contributor: ${{ github.event.pull_request.user.login }}
          contribution-types: code, doc
          skip-ci: true

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CONTRIBUTORS.md
          git commit -m "docs: add ${{ github.event.pull_request.user.login }} to contributors"
          git push
        continue-on-error: true
