name: Greet First-Time PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  greet:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 Welcome @${{ github.actor }}! Thanks for your first contribution! We're excited to have you 🚀"
            })
