name: Greetings

permissions:
  issues: write
  pull-requests: write

on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            🎉 **Thanks for opening your first issue!**

            We're super excited to have you involved in this project!
            Feel free to ask questions, suggest ideas, or even just say hi!

  pr-merge-greeting:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Comment on merged PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const commentBody = `
            🥳 **Congrats on your first merged PR!**

            Your contribution just made this project better!
            You're now officially a contributor — thank you! 🙌  
            We can't wait to see what you build next!
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: commentBody
            });
